#my.datasource.url=local.db.com
#my.datasource.username=username
#my.datasource.password=password
#my.datasource.etc.max-connection=1
#my.datasource.etc.timeout=3500ms
#my.datasource.etc.options=CACHE,ADMIN
my:
  datasource:
    url: local.db.com
    username: local_user
    password: pwd
    etc:
      max-connection: 1
      timeout: 60s
      options: LOCAL, CACHE
---
spring:
  config:
    activate:
      on-profile: dev
my:
  datasource:
    url: dev.db.com
    username: dev_user
    password: pwd
    etc:
      max-connection: 1
      timeout: 60s
      options: LOCAL, CACHE
---
spring:
  config:
    activate:
      on-profile: prd
my:
  datasource:
    url: prd.db.com
    username: prd_user
    password: pwd
    etc:
      max-connection: 1
      timeout: 2s
      options: LOCAL, CACHE
